### ISSUE TITLE
Source generator should respect XAML namescopes.

### ISSUE THREAD

**Issue by maxkatz6** [worldbeater/XamlNameReferenceGenerator#2]
Currently it also generates fields for inner Templates that isn't accessible from the code-behind.

**Comment by worldbeater** [comment]
Probably we should modify tree traversal here https://github.com/worldbeater/XamlNameReferenceGenerator/blob/main/src/XamlNameReferenceGenerator/Infrastructure/MiniNamedControlCollector.cs#L17 and make sure we aren't inside a `DataTemplate` XML element. Should be rather easy to implement, although debugging in source generator land is tricky business (last time was just dumping source generation exceptions to a file)

**Comment by worldbeater** [comment]
A better way to resolve this would be to write a new `IXamlAstTransformer` that would simply strip out the `DataTemplate` elements. A sample tree transformer implementation could be found in https://github.com/worldbeater/XamlNameReferenceGenerator/blob/main/src/XamlNameReferenceGenerator/Infrastructure/NameDirectiveTransformer.cs

**Comment by worldbeater** [comment]
The source generator no longer generates typed references to controls declared inside a `DataTemplate` element. The markup file used for testing purposes is given by [DataTemplates.xaml](https://github.com/worldbeater/XamlNameReferenceGenerator/blob/main/src/XamlNameReferenceGenerator.Tests/Views/DataTemplates.xml) and the test case is given by [Should_Not_Resolve_Elements_From_DataTemplates](https://github.com/worldbeater/XamlNameReferenceGenerator/blob/main/src/XamlNameReferenceGenerator.Tests/NameResolverTests.cs#L90). This was introduced in https://github.com/worldbeater/XamlNameReferenceGenerator/pull/10. Just curious if any other cases exist where it is possible to use `x:Name`, but where the named control won't be accessible from code behind?

**Comment by worldbeater** [comment]
There is a [ControlTemplate](https://github.com/AvaloniaUI/Avalonia/blob/e9d28576aae07f2cd09754a69584f32d2d24218b/src/Avalonia.Themes.Default/MenuItem.xaml#L13) that we have to exclude before closing this I guess.

**Comment by worldbeater** [comment]
Should be resolved now. Feel free to reopen if there are other scenarios we should support.
